variables:
  CI_DESIGNATED_BRANCH: prplos

include:
  - local: .gitlab/build.yml
  - local: .gitlab/cdrouter.yml
  - local: .gitlab/cdrouter/glinet-b1300.yml
  - local: .gitlab/testbed.yml
  - local: .gitlab/testbed/glinet-b1300.yml


stages:
  - run
  - cdrouter

build test ipq40xx prpl webui:
  extends: .build test config

run test Gl.iNet B1300 initramfs:
  needs:
    - job: build test ipq40xx prpl webui
      optional: true
  extends: .glinet-b1300 testbed

