#!/bin/sh /etc/rc.common

USE_PROCD=1

NAME="tr181-display-app2"

start_service() {
    procd_open_instance
    procd_set_param command /usr/bin/prpl_lvgl_demo_app
    procd_set_param env WAYLAND_DISPLAY=/run/cramtestapp2 TEXT_DISPLAY="CRAM TEST APP 2"
    procd_set_param respawn
    procd_close_instance
}
